//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Bibliothecaire.BiblioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ouvrage", Namespace="http://schemas.datacontract.org/2004/07/Servicewcf")]
    [System.SerializableAttribute()]
    public partial class Ouvrage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Code_barreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fiche_descriptiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auteur {
            get {
                return this.AuteurField;
            }
            set {
                if ((object.ReferenceEquals(this.AuteurField, value) != true)) {
                    this.AuteurField = value;
                    this.RaisePropertyChanged("Auteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code_barre {
            get {
                return this.Code_barreField;
            }
            set {
                if ((this.Code_barreField.Equals(value) != true)) {
                    this.Code_barreField = value;
                    this.RaisePropertyChanged("Code_barre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fiche_descriptive {
            get {
                return this.Fiche_descriptiveField;
            }
            set {
                if ((object.ReferenceEquals(this.Fiche_descriptiveField, value) != true)) {
                    this.Fiche_descriptiveField = value;
                    this.RaisePropertyChanged("Fiche_descriptive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((this.StatutField.Equals(value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Theme {
            get {
                return this.ThemeField;
            }
            set {
                if ((object.ReferenceEquals(this.ThemeField, value) != true)) {
                    this.ThemeField = value;
                    this.RaisePropertyChanged("Theme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiblioService.IServiceWCF")]
    public interface IServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/Consulter_List_Ouvrage", ReplyAction="http://tempuri.org/IServiceWCF/Consulter_List_OuvrageResponse")]
        Client_Bibliothecaire.BiblioService.Ouvrage[] Consulter_List_Ouvrage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/Consulter_List_Ouvrage", ReplyAction="http://tempuri.org/IServiceWCF/Consulter_List_OuvrageResponse")]
        System.Threading.Tasks.Task<Client_Bibliothecaire.BiblioService.Ouvrage[]> Consulter_List_OuvrageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/Reserver_Ouvrage", ReplyAction="http://tempuri.org/IServiceWCF/Reserver_OuvrageResponse")]
        bool Reserver_Ouvrage(int codeEmprunteur, int codeOuvrage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/Reserver_Ouvrage", ReplyAction="http://tempuri.org/IServiceWCF/Reserver_OuvrageResponse")]
        System.Threading.Tasks.Task<bool> Reserver_OuvrageAsync(int codeEmprunteur, int codeOuvrage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCFChannel : Client_Bibliothecaire.BiblioService.IServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCFClient : System.ServiceModel.ClientBase<Client_Bibliothecaire.BiblioService.IServiceWCF>, Client_Bibliothecaire.BiblioService.IServiceWCF {
        
        public ServiceWCFClient() {
        }
        
        public ServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client_Bibliothecaire.BiblioService.Ouvrage[] Consulter_List_Ouvrage() {
            return base.Channel.Consulter_List_Ouvrage();
        }
        
        public System.Threading.Tasks.Task<Client_Bibliothecaire.BiblioService.Ouvrage[]> Consulter_List_OuvrageAsync() {
            return base.Channel.Consulter_List_OuvrageAsync();
        }
        
        public bool Reserver_Ouvrage(int codeEmprunteur, int codeOuvrage) {
            return base.Channel.Reserver_Ouvrage(codeEmprunteur, codeOuvrage);
        }
        
        public System.Threading.Tasks.Task<bool> Reserver_OuvrageAsync(int codeEmprunteur, int codeOuvrage) {
            return base.Channel.Reserver_OuvrageAsync(codeEmprunteur, codeOuvrage);
        }
    }
}
